default_platform(:ios)



username = ENV["FASTLANE_USER"]
asc_key_id = ENV["ASC_KEY_ID"]
asc_issuer_id = ENV["ASC_ISSUER_ID"]
asc_key_content = ENV["ASC_KEY_CONTENT"]

team_id = ENV["TEAM_ID"]
scheme = ENV["SCHEME"]
bundle_id = ENV["BUNDLE_ID"]
app_name = ENV["APP_NAME"]
export_method = ENV["EXPORT_METHOD"]

pgy_api_key = ENV["pgy_api_key"]
match_type = export_method.to_s.gsub("-", "")


platform :ios do

  before_all do
    UI.important "Bundle ID: #{ENV['BUNDLE_ID']}"
    UI.important "Scheme: #{ENV['SCHEME']}"
    UI.important "Export method: #{ENV['EXPORT_METHOD']}"
    UI.important "CI: #{is_ci}"
  
    setup_ci if is_ci
  end

  lane :release do
    api_key = on_match
  
    latest_build_number = latest_testflight_build_number(
      api_key: api_key,
      app_identifier: ENV.fetch("BUNDLE_ID"),
      initial_build_number: 0
    )
  
    increment_build_number(
      build_number: latest_build_number + 1,
      xcodeproj: "Kael.xcodeproj"
    )
  
    prepare_gym
  
    gym(
      project: "Kael.xcodeproj",
      scheme: ENV.fetch("SCHEME", "Kael"),
      clean: true,
      export_method: ENV.fetch("EXPORT_METHOD", "app-store"),
      output_directory: "./build",
      output_name: "Kael.ipa"
    )
  
    upload_to_testflight(
      api_key: api_key,
      ipa: "./build/Kael.ipa",
      app_identifier: ENV.fetch("BUNDLE_ID"),
      skip_waiting_for_build_processing: true
    )
  end

  lane :on_match do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_content: ENV.fetch("ASC_KEY_CONTENT"),
      is_key_content_base64: false,
      in_house: false
    )
  
    match(
      git_branch: ENV.fetch("FASTLANE_USER"),
      username: ENV.fetch("FASTLANE_USER"),
      type: "appstore",
      app_identifier: [ENV.fetch("BUNDLE_ID")],
      readonly: false,
      api_key: api_key
    )
  
    api_key
  end

  lane :prepare_gym do

    profile_team_id = ENV["sigh_#{bundle_id}_#{match_type}_team-id"] || team_id
    profile_name = ENV["sigh_#{bundle_id}_#{match_type}_profile-name"] || "match AppStore #{bundle_id}"

    team_id = profile_team_id
    UI.important("Team ID: #{team_id}")

	  UI.important "profile_name = #{profile_name}"

    update_code_signing_settings(
      path: "Kael.xcodeproj",
      use_automatic_signing: false,
      team_id: profile_team_id,
      targets: ["Kael"],
      code_sign_identity: "Apple Distribution",
      profile_name: profile_name,
    )
    

  end

end
